insert into usuario(nome,login,senha,documento,tipoUsuario) values ('cliente1','cliente@email.com','1','1','Cliente');/*1*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('cliente2','cliente2@email.com','1','1','Cliente');/*2*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('restaurante1','restaurante@email.com','1','1','Empresa');/*3*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('entregador','entregador@email.com','1','1','Entregador');/*4*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('cliente3','cliente3@email.com','1','1','Cliente');/*5*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('restaurante2','restaurante2@email.com','1','1','Empresa');/*6*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('entregador2','entregador2@email.com','1','1','Entregador');/*7*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('cliente4','cliente4@email.com','1','1','Cliente');/*8*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('restaurante3','restaurante3@email.com','1','1','Empresa');/*9*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('entregador3','entregador3@email.com','1','1','Entregador');/*10*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('cliente5','cliente5@email.com','1','1','Cliente');/*11*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('restaurante4','restaurante4@email.com','1','1','Empresa');/*12*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('entregador4','entregador4@email.com','1','1','Entregador');/*13*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('cliente6','cliente6@email.com','1','1','Cliente');/*14*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('restaurante5','restaurante5@email.com','1','1','Empresa');/*15*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('entregador5','entregador5@email.com','1','1','Entregador');/*16*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('cliente7','cliente7@email.com','1','1','Cliente');/*17*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('restaurante6','restaurante6@email.com','1','1','Empresa');/*18*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('entregador6','entregador6@email.com','1','1','Entregador');/*19*/