insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email@email.com','2','2','Cliente');/*1*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email2@email.com','2','2','Cliente');/*2*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email3@email.com','2','2','Empresa');/*3*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email4@email.com','2','2','Entregador');/*4*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email5@email.com','2','2','Cliente');/*5*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email6@email.com','2','2','Empresa');/*6*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email7@email.com','2','2','Entregador');/*7*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email8@email.com','2','2','Cliente');/*8*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email9@email.com','2','2','Empresa');/*9*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email10@email.com','2','2','Entregador');/*10*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email11@email.com','2','2','Cliente');/*11*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email12@email.com','2','2','Empresa');/*12*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email13@email.com','2','2','Entregador');/*13*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email14@email.com','2','2','Cliente');/*14*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email15@email.com','2','2','Empresa');/*15*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email16@email.com','2','2','Entregador');/*16*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email17@email.com','2','2','Cliente');/*17*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email18@email.com','2','2','Empresa');/*18*/
insert into usuario(nome,login,senha,documento,tipoUsuario) values ('2','email19@email.com','2','2','Entregador');/*19*/