insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (3,'x-tudo','hamburguer','hamburguer',10,10,'Disponivel');/*20*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (6,'calabreza','pizza','pizza',10,10,'Disponivel');/*21*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (9,'salada','vegetariano','vegetariano',10,10,'Disponivel');/*22*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (12,'x-tudo','hamburguer','hamburguer',10,10,'Disponivel');/*23*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (15,'calabreza','pizza','pizza',10,10,'Disponivel');/*24*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (18,'salada','vegetariano','vegetariano',10,10,'Disponivel');/*25*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (18,'x-tudo','hamburguer','hamburguer',10,10,'Disponivel');/*26*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (18,'calabreza','pizza','pizza',10,10,'Disponivel');/*27*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (3,'salada','vegetariano','vegetariano',10,10,'Disponivel');/*28*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (6,'x-tudo','hamburguer','hamburguer',10,10,'Disponivel');/*29*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (9,'calabreza','pizza','pizza',10,10,'Disponivel');/*30*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (15,'salada','vegetariano','vegetariano',10,10,'Disponivel');/*31*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (18,'x-tudo','hamburguer','hamburguer',10,10,'Disponivel');/*32*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (6,'calabreza','pizza','pizza',10,10,'Disponivel');/*33*/
insert into produto(id_empresa,nome,categoria,descricao,quantidade,preco,estado) values (9,'salada','vegetariano','vegetariano',10,10,'Disponivel');/*34*/