insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (1,'1','A','B','C','D','E','Avenida','G');/*35*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (2,'1','A','B','C','D','E','Fazenda','G');/*36*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (5,'1','A','B','C','D','E','Rua','G');/*37*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (8,'1','A','B','C','D','E','Avenida','G');/*38*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (11,'1','A','B','C','D','E','Fazenda','G');/*39*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (14,'1','A','B','C','D','E','Rua','G');/*40*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (17,'1','A','B','C','D','E','Avenida','G');/*41*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (1,'1','A','B','C','D','E','Fazenda','G');/*42*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (2,'1','A','B','C','D','E','Rua','G');/*43*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (5,'1','A','B','C','D','E','Avenida','G');/*44*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (9,'1','A','B','C','D','E','Fazenda','G');/*45*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (11,'1','A','B','C','D','E','Rua','G');/*46*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (14,'1','A','B','C','D','E','Avenida','G');/*47*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (17,'1','A','B','C','D','E','Fazenda','G');/*48*/
insert into endereco(id_usuario,numero,complemento,logradouro,bairro,cidade,estado,tipoEndereco,cep) values (3,'1','A','B','C','D','E','Rua','G');/*49*/